import Foundation

func field(_ label: String, autocomplete: String = "", length: Int = 0, occupied: Bool = false, options: [FormField.Option] = [], pattern: String = "", context: String = "", name: String = "", type: String = "text", placeholder: String = "") -> FormField {
    FormField(id: "f0", tag: options.isEmpty ? "input" : "select", type: options.isEmpty ? type : "select-one", label: label, ariaLabel: "", name: name, htmlID: "", placeholder: placeholder, autocomplete: autocomplete, context: context, maxLength: length, pattern: pattern, occupied: occupied, options: options)
}
func plan(_ field: FormField, _ kind: FieldKind) -> [String: Any] {
    FillPlanner.plan(fields: [field], kinds: ["f0": kind], sources: ["f0": "rule"], modelFailed: false)
}
func value(_ field: FormField, _ kind: FieldKind) -> String? { (plan(field, kind)["items"] as? [[String: Any]])?.first?["value"] as? String }
assert(FillPlanner.rule(for: field("姓")) == .family)
assert(FillPlanner.rule(for: field("セイ")) == .familyKana)
assert(FillPlanner.rule(for: field("姓（ふりがな）")) == .familyKana)
assert(FillPlanner.rule(for: field("町名・番地", autocomplete: "address-line1")) == .localityStreet)
assert(FillPlanner.rule(for: field("住所1", autocomplete: "address-line1")) == nil)
assert(FillPlanner.rule(for: field("郵便番号", length: 3)) == .postalFirst3)
assert(value(field("せい"), .familyKana) == "やまだ")
assert(value(field("番地"), .street) == "1-1")
assert(value(field("町名・番地"), .localityStreet) == "千代田1-1")
assert(value(field("郵便番号"), .postal) == "100-0001")
assert(value(field("郵便番号", length: 7), .postal) == "1000001")
assert(value(field("郵便番号", pattern: "[0-9]{7}"), .postal) == "1000001")
assert(value(field("郵便番号", pattern: "[0-9]{3}-[0-9]{4}"), .postal) == "100-0001")
assert(value(field("姓", length: 1), .family) == nil)
assert(value(field("姓", occupied: true), .family) == nil)
assert(value(field("不明"), .unknown) == nil)
assert(value(field("都道府県", options: [.init(value: "13", text: "東京都", disabled: false)]), .prefecture) == "13")
assert(value(field("都道府県", options: [.init(value: "13", text: "大阪府", disabled: false)]), .prefecture) == nil)
assert(value(field("都道府県", options: [.init(value: "13", text: "東京都", disabled: true)]), .prefecture) == nil)
let valid: [String: Any] = ["version": 1, "type": "analyzeForm", "requestID": UUID().uuidString, "fields": try! JSONSerialization.jsonObject(with: JSONEncoder().encode([field("姓")]))]
assert(FillPlanner.decode(valid) != nil)
var invalid = valid; invalid["requestID"] = "not-a-uuid"; assert(FillPlanner.decode(invalid) == nil)
invalid = valid; invalid["fields"] = try! JSONSerialization.jsonObject(with: JSONEncoder().encode([field("姓"), field("名")]))
assert(FillPlanner.decode(invalid) == nil)
assert(FillPlanner.rule(for: field("住所1（町名・番地）")) == .localityStreet)
assert(FillPlanner.rule(for: field("住所1（市区町村・町名・番地）")) == .municipalityLocalityStreet)
assert(FillPlanner.rule(for: field("住所2（建物名・部屋番号）")) == .building)
assert(FillPlanner.rule(for: field("姓", context: "フリガナ")) == .familyKana)
assert(FillPlanner.rule(for: field("名", context: "フリガナ")) == .givenKana)
assert(FillPlanner.rule(for: field("フリガナ(姓)")) == .familyKana)
assert(FillPlanner.rule(for: field("お名前(名)")) == .given)
assert(FillPlanner.rule(for: field("", length: 4, name: "c_f_zip_no[1]")) == .postalLast4)
assert(FillPlanner.rule(for: field("市区町村・番地")) == .municipalityLocalityStreet)
assert(FillPlanner.rule(for: field("住所（都道府県）")) == .prefecture)
assert(FillPlanner.rule(for: field("市区町村", placeholder: "例) 京都市右京区西院巽町")) == .municipalityLocality)
assert(value(field("市区町村"), .municipalityLocality) == "千代田区千代田")
assert(value(field("ご住所", name: "zip", type: "tel"), .postal) == "1000001")
invalid = valid; invalid["fields"] = try! JSONSerialization.jsonObject(with: JSONEncoder().encode([field("ご住所", name: "zip", type: "tel")]))
assert(FillPlanner.decode(invalid) != nil)
invalid["fields"] = try! JSONSerialization.jsonObject(with: JSONEncoder().encode([field("電話番号", name: "tel", type: "tel")]))
assert(FillPlanner.decode(invalid) == nil)
assert(FillPlanner.rule(for: field("住所（市区町村郡以降） 例：山形市清住町3-2-45")) == .addressWithoutPrefecture)
assert(FillPlanner.rule(for: field("市区町村", placeholder: "例：千代田区")) == nil)
assert(FillPlanner.rule(for: field("ご連絡先の電話番号 例：022-123-4567")) == .unknown)
assert(FillPlanner.rule(for: field("メールアドレス")) == .unknown)
assert(FillPlanner.rule(for: field("会社名")) == .unknown)
assert(FillPlanner.rule(for: field("お問い合わせ内容")) == .unknown)
let prefectures: [FormField.Option] = [.init(value: "13", text: "東京都", disabled: false), .init(value: "14", text: "神奈川県", disabled: false)]
assert(FillPlanner.rule(for: field("", occupied: true, options: prefectures)) == .prefecture)
assert(value(field("都道府県", occupied: true, options: prefectures), .prefecture) == "13")
assert(value(field("市区町村", occupied: true), .municipality) == nil)
assert(value(field("選択", occupied: true, options: [.init(value: "x", text: "その他", disabled: false)]), .prefecture) == nil)
print("Native fill planner: 47 checks passed")
